# Generated by Django 3.1.6 on 2023-06-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TourOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('stream', models.IntegerField(choices=[(1, 'viator'), (2, 'airbnb'), (3, 'tripadvisor'), (4, 'expedia'), (5, 'klook'), (6, 'civitatis'), (7, 'getyourguide'), (8, 'facebook'), (9, 'google'), (10, 'instagram'), (11, 'linkedin')], default=1)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_urls', to='api.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.touroperator'),
        ),
    ]
