# Generated by Django 3.1.6 on 2023-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230614_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroperator',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
