# Generated by Django 3.1.6 on 2023-06-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toururl',
            name='url',
            field=models.CharField(max_length=10240),
        ),
    ]
