# Generated by Django 3.1.6 on 2023-06-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230620_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non Classified')], default=0),
        ),
    ]
