# Generated by Django 3.1.6 on 2023-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tour_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
