# Generated by Django 3.1.6 on 2023-07-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230701_2043'),
        ('api', '0011_auto_20230630_0714'),
    ]

    operations = [
    ]
