# Generated by Django 3.1.6 on 2023-10-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230817_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
    ]
