# Generated by Django 3.1.6 on 2023-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
