# Generated by Django 3.1.6 on 2023-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non Classified')], default=0),
        ),
    ]
