# Generated by Django 3.1.6 on 2023-06-14 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230614_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
