# Generated by Django 3.1.6 on 2023-06-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230614_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toururl',
            name='stream',
            field=models.IntegerField(choices=[(1, 'viator'), (2, 'airbnb'), (3, 'tripadvisor'), (4, 'expedia'), (5, 'klook'), (6, 'civitatis'), (7, 'getyourguide'), (8, 'facebook'), (9, 'google'), (10, 'instagram'), (11, 'linkedin'), (12, 'tiquets')], default=1),
        ),
    ]
