# Generated by Django 3.1.6 on 2023-07-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_review_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='n_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='api.tour'),
        ),
    ]
